---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secret
  namespace: tasktracker-gitops
spec:
  encryptedData:
    DATABASE_URL: AgAbvy7suDNxkLbo3B9QzKeCBKDJzwLgzYBKfqHHCi3dxfCAh1IgFPuuMo9uTOdUXWjs/7BrZVrHxXu/mOmcEriRplsQOzebv66iU/aWtBFM5dU9b5gV+bWTyvjekiNDTz3s9sdLDEnskW/bQajxE2VSyQi3tHMC4iVwV37XtY30SggS6h4ZIXAGGT/h1Vhi1eppoNhr295VM1WReJXz3c0ATk2xXx1t7CaRAJ68EEYkn1+8nlA7CLC1Dr0fl4TTGf63+QrHTLjT7P6UwnjDfVftBbMNazJiceZluK6iLjQKLLlFrkRrhIZjpgRAJ6ekUi1jMTEIAt/towaMAC0vwndewzc7JkNQC0kyU+aeqd427PtU7nhpHLGBD2aM8Nl4cefRGvQgrdirpqab4KKC8C5EIsakxLVwDRe9KoCNwwAXo3Zvd2kv+JkPnbnd7mYW8M4jAv1JdXvLYgtBg8n1HRuYRkUAt+MBxTQ1C7FooXZ0Lep5lLLODV7FZyettQcNc7lE1OhYGRM+JnZQ9f8CQpmIt0RKcL2KeiqFfknDDPGV3gvshDCqzAy1nTZeqqINDJIwWZO1mpyACtnsUHhB7WXmgLN4WYoekPLjaQ0rzsXkj4BNfWhs4Bk+WG77iURHxjlUzp2moFhOQn8OaupsFCCNA72hvglMdoUt0KetnYqWDakGxpKSi7rArITvpj/uFvWP9jWzEnnaPyQYgLDcjilEeLlIvzBqoFrc/xHHqI5ableikGL1K6spMPSFgOijMSyjyhpCjz7iEYJv8WCAxEn4
  template:
    metadata:
      annotations:
        argocd.argoproj.io/tracking-id: tasktracker:/Secret:tasktracker/backend-secret
      name: backend-secret
      namespace: tasktracker-gitops
    type: Opaque
