---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-smtp-secret
  namespace: monitoring
spec:
  encryptedData:
    GF_SMTP_PASSWORD: AgAOSo3d0GTnMOvIGN+doSmlYd/B3X4MnLKKQUWh4cT2/TsNP8c94HEPNmtcvCTw5bhYxFm8qo6RQuLcm370phG2Phf8fPyitaSfp0ZBFTmKS6CzHQ5L2vhO3N5vQEIjya1ILGxZCIQvtHULHh8Xic5VAc7UFW5H0nz2pFSkSeICQRlCwQ3TzmgiHldIRGzCnG0Uw1n0WbIrXCO8CPptgrqWFgiskCW459E0fgrpZy9oQh4n65lePbWW3enfzeebEZ4NJjE7ZsA7oHXY3KYE6pfprSr5SPB6oe8f29ZFCm3HB2FVgYEq4U6+Lqc6NfaA8pSgHYxKrQPPwcCNSUCUMvuzhetj8C2bVa+9i1/m2jY9uAZ1kLupgz/js660HgIZZaaUixzlk1W0argU4ybjoOv476MPk6WA+OnSoz41MkzWQ9jyN5xq4I5AELVpWaHBa42Q+zGQX3ZCXLqnmQzh55p0FkzrIz+POpvYCOeKvjDRAUy3ZlqP01a/p22nZiq90ykv6ool3ymWDrDwkx4ssPenKEYMf3MHdkfQjMa6GzH4LQn8eV7Sfp9SiIpClWiKRJyfR0+YvmcQ6mLWoO1uBXSA2JuQjsI+cCsCLJ8gtHXXF6iLz5uvHRIfoz75MZwJ05KyHDdR5LHBcpt7C+dGZDAb6sn1UkrRT+xSd8C6ycsVom5hBt71nWfVz+4ZkGHv+387pCeHjaGx59zqYXrkEPRUn0GN
    GF_SMTP_USER: AgCMmkpw+2ITK+L5Loz0PBQgY+HA/MDPJYnH9T7EUYKKyfyNl0tVwyjmJp6qAK0B6RhMYRztcM6pQ9cvT702Arz+wlgcZL4Yto2CD7pS4GOMC6aSVfW9Mwt3SkfLmrumgbvYRb8BL2tg5jYD6bqvLD408HdUgTEIOADtndMPO2DQcEIijMwBX/f399po8Z8SiTQFRwhDxY9mPY/IiNYrxBv6DlyiQM5LcBbv8bQ37AZkBX75MjX9DFmEiFNqjSW7+AVWlunFIX1REoGPnCGOOeh5DzuIKPF2z8TIxeLOOjA6fzbUuNvzOzs8D0daNEaz3mEY4Q+SdGPBheNo7WV7cYvnp6Jbv7775x2+BkBLQ6NFz6fF9rgQUf2qpVgAfgEWzg0eGuynNOsZoHZ4n3zSdiXohhS7n5LtTLXQUIoU2R9JwruAuZooN1hCvPJCaHhseYGufe29CHG2OfhloyUovuF1q4iBLB3cHxkw8zvOdYaHm/aHTa7+fH65DUgo/a8R2nzpgVxPYQh+MAFCdy6kdGOw7Re67k5T8VfvUgcVhI3IrueTURPZENXJP9apoqDwj37hXQ/OAt7RHqc6tx9i6aO0k7ibWC3KBBV6zvbEBJN3stXOYLxxyPpSqFWz6Foewq3nXomKcVranyyaJcsMC9gF/p5m9D4ZkGDpvXTGtZiAJwwedy2IlgMDoPj6XT6qyDXPJE2ldfsmufNh+v6O7rJuN/H3oalRrdQ=
  template:
    metadata:
      name: grafana-smtp-secret
      namespace: monitoring
