apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: {{ include "tasktracker.postgres.pvcName" . }}

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}
