apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasktracker-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasktracker-backend
  template:
    metadata:
      labels:
        app: tasktracker-backend
    spec:
      containers:
        - name: backend
          image: shukratolaitan/tasktracker-backend:v4
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: DATABASE_URL
              value: postgresql+psycopg://postgres:password@postgres:5432/tasktracker
