name: Build Backend Image

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend-image.yaml"
      - "kubernetes/base/backend-deployment.yaml"
  permissions:
    contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: shukratolaitan/tasktracker-backend:${{ github.sha }}
      
      - name: Update Kubernetes image tag
        run: |
          sed -i "s|image: shukratolaitan/tasktracker-backend:.*|image: shukratolaitan/tasktracker-backend:${{ github.sha }}|" kubernetes/base/backend-deployment.yaml

      - name: Commit updated image tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add kubernetes/base/backend-deployment.yaml
          git commit -m "Update backend image to ${{ github.sha }}" || echo "No changes to commit"
          git push
